CREATE TABLE BASKET(
  ID SERIAL PRIMARY KEY
, FRUIT VARCHAR(50) NOT NULL
);

INSERT INTO BASKET(FRUIT) VALUES('APPLE');
INSERT INTO BASKET(FRUIT) VALUES('APPLE');
INSERT INTO BASKET(FRUIT) VALUES('ORANGE');
INSERT INTO BASKET(FRUIT) VALUES('ORANGE');
INSERT INTO BASKET(FRUIT) VALUES('ORANGE');
INSERT INTO BASKET(FRUIT) VALUES('BANANA');

COMMIT; 

SELECT * FROM BASKET; 

|id|fruit 
|--|------
| 1|APPLE 
| 2|APPLE 
| 3|ORANGE
| 4|ORANGE
| 5|ORANGE
| 6|BANANA
;

SELECT
	ID, FRUIT, ROW_NUM
FROM
	(
		SELECT 
			   ID
			 , FRUIT 
		     , ROW_NUMBER() OVER( PARTITION BY FRUIT ORDER BY ID ASC) AS ROW_NUM
	      FROM BASKET ) T
WHERE
	T.ROW_NUM > 1 ;

|id|fruit |row_num
|--|------|-------
| 2|APPLE |      2
| 4|ORANGE|      2
| 5|ORANGE|      3

DELETE FROM BASKET
WHERE ID IN 
(SELECT
	   ID
   FROM
	  (
		SELECT 
			   ID
			 , FRUIT 
		     , ROW_NUMBER() OVER( PARTITION BY FRUIT ORDER BY ID ASC) AS ROW_NUM
	      FROM BASKET ) T
  WHERE T.ROW_NUM > 1);
  
 COMMIT; 
 
SELECT * FROM BASKET; 

|id|fruit 
|--|------
| 1|APPLE 
| 3|ORANGE
| 6|BANANA