문제1번)  상품별 주문 수 와 전체 주문수를 함께 보여주세요.

     답 SQL 은 여기 
     
    SELECT PRODUCTNUMBER , COUNT(DISTINCT ORDERNUMBER ) AS ORDER_COUNT
      FROM ORDER_DETAILS OD 
    GROUP BY PRODUCTNUMBER 
    UNION ALL 
    SELECT NULL, COUNT(DISTINCT ORDERNUMBER ) AS ORDER_COUNT
      FROM ORDER_DETAILS OD 
    ORDER BY PRODUCTNUMBER 
     

문제2번)  상품 이름과 카테고리별 전체 매출액을 알려주세요.또한, 카테고리별 전체 매출액 도 함께 알려주세요.

     답 SQL 은 여기 


  SELECT C.CATEGORYDESCRIPTION
     , P.PRODUCTNAME
     , SUM(OD.QUOTEDPRICE * OD.QUANTITYORDERED ) AS TOTAL_PRICE
  FROM ORDER_DETAILS OD 
INNER JOIN PRODUCTS P ON P.PRODUCTNUMBER  = OD.PRODUCTNUMBER 
INNER JOIN CATEGORIES C ON P.CATEGORYID = C.CATEGORYID 
GROUP BY GROUPING SETS ((C.CATEGORYDESCRIPTION , P.PRODUCTNAME ), (C.CATEGORYDESCRIPTION))
ORDER BY C.CATEGORYDESCRIPTION , P.PRODUCTNAME    
    





.제3번) 자전거 카테고리 주문 량이 매달 증가하고 있나요? (2017년 1월 ~ 12월 까지 판매량만 /확인하시면 됩니다.)
 월별 주문량을 이전 달 주문량과 함께 표기해 증가 여부를 알려주세요. (analytic function 활용       
 
 ) 


-- Hint 아래의 표기 값으로 산출 해주세요. 
-- 1) 전 달 보다 값이 크다면 ? 'PLUS’
-- 2) 이전 달의 값이 현재 값 보다 크다면 ? 'MINUS’
-- 3) 현재 달의 판매 량과 이전 달 값이 같다면 ? 'SAME’
-- 4) 이 외의 Case ? NULL


   --   답 SQL 은 여기 


	      
SELECT 
	  MM
	, LAST_ORDER_COUNT
	, ORDER_COUNT
	, CASE 
			WHEN LAST_ORDER_COUNT < ORDER_COUNT THEN 'PLUS'
	  		WHEN LAST_ORDER_COUNT > ORDER_COUNT THEN 'MINUS'
	  		WHEN LAST_ORDER_COUNT = ORDER_COUNT THEN 'SAME'
	  		ELSE NULL
	  END AS COMPARE_FLAG 		
FROM 
	(  
		SELECT 
				TO_CHAR (O.ORDERDATE, 'YYYYMM') MM
		      , CAST(COUNT(DISTINCT O.ORDERNUMBER ) AS INTEGER) ORDER_COUNT
		      , LAG(CAST(COUNT(DISTINCT O.ORDERNUMBER ) AS INTEGER), 1) OVER() AS LAST_ORDER_COUNT
	      FROM ORDERS O
		 INNER JOIN ORDER_DETAILS OD ON OD.ORDERNUMBER  = O.ORDERNUMBER 
		 INNER JOIN PRODUCTS P ON OD.PRODUCTNUMBER = P.PRODUCTNUMBER 
		 INNER JOIN CATEGORIES C ON P.CATEGORYID = C.CATEGORYID 
		 WHERE C.CATEGORYID = 2
		   AND O.ORDERDATE BETWEEN '2017-01-01' AND '2017-12-31'
		 GROUP BY TO_CHAR(O.ORDERDATE, 'YYYYMM')
	 ) A
       
     
	 
	 
문제4번) 제품 카테고리, 주(state) 기준으로 보유한 물량을 보여주고, 주(state) 전체 보유물량도 함께 나열하세요. (analytic function 활용)

 
    답 SQL 은 여기 
    
 		SELECT 
    		  DISTINCT C.CATEGORYDESCRIPTION 
    		, V2.VENDSTATE 
    		, SUM(P.QUANTITYONHAND) OVER(PARTITION BY C.CATEGORYDESCRIPTION, V2.VENDSTATE ) AS QUANTITYONHAND_BY_STATE
    		, SUM(P.QUANTITYONHAND) OVER(PARTITION BY V2.VENDSTATE ) AS QUANTITYONHAND_BY_STATE
         FROM PRODUCTS P 
       INNER JOIN PRODUCT_VENDORS PV ON PV.PRODUCTNUMBER = P.PRODUCTNUMBER 
       INNER JOIN VENDORS V2 ON V2.VENDORID = PV.VENDORID 
       INNER JOIN CATEGORIES C ON P.CATEGORYID = C.CATEGORYID 
       ORDER BY C.CATEGORYDESCRIPTION 
              , V2.VENDSTATE     
    


문제5번)  주문일자가 2017/09/01 ~ 2017/12/31 일에 해당하는 주문 에 대해서,  월별 고객별 결제 금액을 기준으로 결제 금액에 대한 flag 를 함께 보여주세요. 
flag 는 아래와 같습니다.

- 고객의 결제금액이 10000 달러 아래에 경우 under1000
- 고객의 결제금액이 10001 ~ 100000 에 해당하는 경우 under100000 
- 고객의 결제금액이 100001 ~ 500000에 해당하는 경우 under500000
- 고객의 결제금액이 500001 이상인 경우 over500000


     답 SQL 은 여기 

     
 SELECT  
 		   TO_CHAR(O.ORDERDATE, 'YYYYMM')
         , CUSTOMERID 
         , SUM(OD.QUOTEDPRICE)
         , CASE 
         		WHEN SUM(OD.QUOTEDPRICE) <= 10000 THEN 'UNDER10000'
         		WHEN SUM(OD.QUOTEDPRICE) >=  10001 AND SUM(OD.QUOTEDPRICE) <= 100000 THEN 'UNDER100000'
         		WHEN SUM(OD.QUOTEDPRICE) >= 100001 AND SUM(OD.QUOTEDPRICE) <= 500000 THEN 'UNDER500000'
         		WHEN SUM(OD.QUOTEDPRICE) >= 500001 THEN 'OVER500000'
         		ELSE NULL
     	   END AS FLAG
   FROM ORDERS O
 INNER JOIN ORDER_DETAILS OD ON O.ORDERNUMBER = OD.ORDERNUMBER 
  WHERE O.ORDERDATE BETWEEN '2017-09-01' AND '2017-12-31'
 GROUP BY TO_CHAR(O.ORDERDATE, 'YYYYMM')
         , CUSTOMERID 
 ORDER BY  TO_CHAR(O.ORDERDATE, 'YYYYMM')
         , CUSTOMERID 
         
